import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('heading', { level: 1 }).waitFor();
await page.screenshot({ path: '.work/home-desktop.png', fullPage: true });
await page.goto('http://127.0.0.1:5173/#/read/202');
await page.locator('#source-page-202 .native-content').waitFor();
await page.screenshot({ path: '.work/reader-desktop.png', fullPage: false });
await page.getByRole('button', { name: 'Original page', exact: true }).click();
await page.locator('canvas').waitFor();
await page.waitForFunction(() => document.querySelector('canvas')?.height > 100);
await page.waitForTimeout(1800);
await page.screenshot({ path: '.work/pdf-desktop.png', fullPage: false });
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('heading', { level: 1 }).waitFor();
await page.screenshot({ path: '.work/home-mobile.png', fullPage: true });
await page.goto('http://127.0.0.1:5173/#/read/202');
await page.locator('#source-page-202 .native-content').waitFor();
await page.screenshot({ path: '.work/reader-mobile.png', fullPage: false });
console.log(JSON.stringify({ errors, overflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }));
await browser.close();
